import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
  id "com.github.mxenabled.coppuccino" version "8.+"
  id "groovy"
  id "java-gradle-plugin"
  id "maven-publish"
  id "org.jetbrains.kotlin.jvm" version "2.3.0"
}

group "com.mx.vogue"
version "5.0.0" // x-release-please-version

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

kotlin {
  compilerOptions {
    jvmTarget = JvmTarget.JVM_21
  }
}

coppuccino {
  kotlin { enabled = true }
  coverage {
    minimumCoverage = 0.73
    excludes = [
      "com/mx/vogue/core/models/**"
    ]
  }
}

repositories {
  mavenCentral()
  mavenLocal()
  gradlePluginPortal()
}

dependencies {
  implementation "com.google.code.gson:gson:[2.0,3.0)"
  implementation "tools.jackson.dataformat:jackson-dataformat-yaml:[3.1.4,4.0.0)"
  implementation "com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.54.0"

  testImplementation "org.mockito:mockito-core:[5.0,6.0)"
  testImplementation "org.spockframework:spock-core:2.4-groovy-4.0"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test { useJUnitPlatform() }

gradlePlugin {
  plugins {
    voguePlugin {
      id = group
      implementationClass = "com.mx.vogue.VoguePlugin"
    }
    vogueJitPackPlugin {
      id = "com.github.mxenabled.vogue"
      implementationClass = "com.mx.vogue.VoguePlugin"
    }
  }
}

wrapper {
  gradleVersion = "9.5.1"
  distributionType = Wrapper.DistributionType.ALL
}
