package com.mx.vogue.core.models

data class Available(
  val release: String,
  val milestone: String,
  val integration: String
)

data class VersionsPluginDependency(
  val group: String,
  val version: String,
  val available: Available,
  val name: String
)

data class VersionsPluginItem(
  val dependencies: List<VersionsPluginDependency>,
  val count: Int
)

/**
 * Models the JSON report generated by: https://github.com/ben-manes/gradle-versions-plugin
 */
data class VersionsPluginReport(
  val current: VersionsPluginItem,
  val exceeded: VersionsPluginItem,
  val outdated: VersionsPluginItem,
  val unresolved: VersionsPluginItem,
  val count: Int
)
