/**
 * Copyright 2020 MX Technologies.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mx.vogue.core.models

data class Available(
  val release: String,
  val milestone: String,
  val integration: String
)

data class VersionsPluginDependency(
  val group: String,
  val version: String,
  val available: Available,
  val name: String
)

data class VersionsPluginItem(
  val dependencies: List<VersionsPluginDependency>,
  val count: Int
)

/**
 * Models the JSON report generated by: https://github.com/ben-manes/gradle-versions-plugin
 */
data class VersionsPluginReport(
  val current: VersionsPluginItem,
  val exceeded: VersionsPluginItem,
  val outdated: VersionsPluginItem,
  val unresolved: VersionsPluginItem,
  val count: Int
)
